def exception_check(a, b):
    ...